from wan.kernels.flash_attention_v4 import flash_attn_varlen_func as fa4_flash_attn_varlen_func


def flash_attn_varlen_func(
  q,
  k,
  v,
  cu_seqlens_q,
  cu_seqlens_k,
  max_seqlen_q=None,
  max_seqlen_k=None,
  seqused_q=None,
  seqused_k=None,
  page_table=None,
  softmax_scale=None,
  causal=False,
  qv=None,
  q_descale=None,
  k_descale=None,
  v_descale=None,
  window_size=(-1, -1),
  attention_chunk=0,
  softcap=0.0,
  num_splits=1,
  pack_gqa=None,
  sm_margin=0,
  sinks=None,
  score_mod=None,
  aux_tensors=None,
  out=None,
):
  return fa4_flash_attn_varlen_func(
    q,
    k,
    v,
    cu_seqlens_q,
    cu_seqlens_k,
    max_seqlen_q=max_seqlen_q,
    max_seqlen_k=max_seqlen_k,
    seqused_q=seqused_q,
    seqused_k=seqused_k,
    page_table=page_table,
    softmax_scale=softmax_scale,
    causal=causal,
    softcap=softcap,
    window_size=window_size,
    sinks=sinks,
    num_splits=num_splits,
    pack_gqa=pack_gqa,
    score_mod=score_mod,
    aux_tensors=aux_tensors,
  )
